# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(223, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gen_pwd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gen_pwd_btn.setGeometry(QtCore.QRect(30, 90, 161, 51))
        self.gen_pwd_btn.setObjectName("gen_pwd_btn")
        self.pwd_label = QtWidgets.QLabel(self.centralwidget)
        self.pwd_label.setGeometry(QtCore.QRect(20, 160, 191, 51))
        self.pwd_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pwd_label.setScaledContents(True)
        self.pwd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pwd_label.setObjectName("pwd_label")
        self.save_pwd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_pwd_btn.setGeometry(QtCore.QRect(30, 240, 161, 51))
        self.save_pwd_btn.setObjectName("save_pwd_btn")
        self.website_info = QtWidgets.QLineEdit(self.centralwidget)
        self.website_info.setGeometry(QtCore.QRect(30, 60, 161, 20))
        self.website_info.setObjectName("website_info")
        self.website_info_label = QtWidgets.QLabel(self.centralwidget)
        self.website_info_label.setGeometry(QtCore.QRect(40, 30, 151, 16))
        self.website_info_label.setObjectName("website_info_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 223, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gen_pwd_btn.setText(_translate("MainWindow", "Generate Password"))
        self.pwd_label.setText(_translate("MainWindow", "Your password will appear here"))
        self.save_pwd_btn.setText(_translate("MainWindow", "Save Password"))
        self.website_info_label.setText(_translate("MainWindow", "Add website to the box below"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
