# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manager_widget(object):
    def setupUi(self, manager_widget):
        manager_widget.setObjectName("manager_widget")
        manager_widget.setEnabled(True)
        manager_widget.resize(592, 462)
        self.data_table = QtWidgets.QTableView(manager_widget)
        self.data_table.setGeometry(QtCore.QRect(10, 30, 561, 401))
        self.data_table.setObjectName("data_table")
        self.pwd_info = QtWidgets.QLabel(manager_widget)
        self.pwd_info.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.pwd_info.setObjectName("pwd_info")

        self.retranslateUi(manager_widget)
        QtCore.QMetaObject.connectSlotsByName(manager_widget)

    def retranslateUi(self, manager_widget):
        _translate = QtCore.QCoreApplication.translate
        manager_widget.setWindowTitle(_translate("manager_widget", "Form"))
        self.pwd_info.setText(_translate("manager_widget", "Password view"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manager_widget = QtWidgets.QWidget()
    ui = Ui_manager_widget()
    ui.setupUi(manager_widget)
    manager_widget.show()
    sys.exit(app.exec_())
